name: cork_example

environment:
  sdk: ">=3.0.0"

dependencies:
  cork_site:
    path: ../
  build: any
dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  lints: ^6.0.0
  web: any

cork_rss:
  title: "Cork Site"
  description: "A minimalist personal static site generator"
  base_url: "https://example.com"
  language: "en-us"
  copyright: "© 2025 Cork Site"
  author:
    name: "Cork User"
    email: "user@example.com"
  max_items: 20
