name: cork_example

environment:
  sdk: ">=3.0.0"

dependencies:
  cork_site:
    path: ../
  build: any
dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  lints: ^6.0.0
  web: any
