name: cork
description: A minimalist personal static site generator
version: 0.0.1
homepage: https://github.com/jasonrdsouza/cork
repository: https://github.com/jasonrdsouza/cork
author: Jason Dsouza <jasonrdsouza@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^1.0.0
  path: ^1.6.0
  glob: ^1.1.0
  markdown: ^2.0.0
  yaml: ^2.1.0
  mustache: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.0.0
